# Generated by Django 2.2 on 2019-06-28 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('yearId', models.AutoField(primary_key=True, serialize=False)),
                ('yearName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchId', models.AutoField(primary_key=True, serialize=False)),
                ('branchName', models.CharField(choices=[('Computer', 'Computer'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Electronics', 'Electronics')], help_text='Branch', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyId', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender', max_length=10, null=True)),
                ('branchId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='FacultyBranchId', to='ams.Branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_faculty', 'is_faculty'),),
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterId', models.AutoField(primary_key=True, serialize=False)),
                ('semesterName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('rollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender', max_length=10, null=True)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentBranchId', to='ams.Branch')),
                ('semesterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentSemesterId', to='ams.Semester')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AcademicYearId', to='ams.AcademicYear')),
            ],
            options={
                'ordering': ['-user'],
                'permissions': (('is_student', 'is_student'),),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=255)),
                ('subjectShortName', models.CharField(max_length=255)),
                ('branchId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubjectBranchId', to='ams.Branch')),
                ('semesterId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubjectSemesterId', to='ams.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectByFaculty',
            fields=[
                ('subjectByFacultyId', models.AutoField(primary_key=True, serialize=False)),
                ('facultyId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubjectByFacultyfacultyId', to='ams.Faculty')),
                ('subjectId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubjectByFacultysubjectId', to='ams.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentByClass',
            fields=[
                ('rollNo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ams.Students')),
                ('branchId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentByClassbranchId', to='ams.Branch')),
                ('semesterId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentByClasssemesterId', to='ams.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('branchId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='AttendancebranchId', to='ams.Branch')),
                ('semesterId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='AttendancesemesterId', to='ams.Semester')),
                ('subjectByFacultyId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='AttendancesubjectByFacultyId', to='ams.SubjectByFaculty')),
                ('studentByClassRollNo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='AttendancestudentByClassId', to='ams.StudentByClass')),
            ],
        ),
    ]
